/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelosIndexRouteImport } from './routes/modelos/index'
import { Route as ModelosModeloIdRouteImport } from './routes/modelos/$modeloId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosIndexRoute = ModelosIndexRouteImport.update({
  id: '/modelos/',
  path: '/modelos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosModeloIdRoute = ModelosModeloIdRouteImport.update({
  id: '/modelos/$modeloId',
  path: '/modelos/$modeloId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modelos/$modeloId': typeof ModelosModeloIdRoute
  '/modelos': typeof ModelosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modelos/$modeloId': typeof ModelosModeloIdRoute
  '/modelos': typeof ModelosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modelos/$modeloId': typeof ModelosModeloIdRoute
  '/modelos/': typeof ModelosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/modelos/$modeloId' | '/modelos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modelos/$modeloId' | '/modelos'
  id: '__root__' | '/' | '/modelos/$modeloId' | '/modelos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModelosModeloIdRoute: typeof ModelosModeloIdRoute
  ModelosIndexRoute: typeof ModelosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos/': {
      id: '/modelos/'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos/$modeloId': {
      id: '/modelos/$modeloId'
      path: '/modelos/$modeloId'
      fullPath: '/modelos/$modeloId'
      preLoaderRoute: typeof ModelosModeloIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModelosModeloIdRoute: ModelosModeloIdRoute,
  ModelosIndexRoute: ModelosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
